<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>6.2138.v03274d462c13</version>
    <relativePath />
  </parent>

  <artifactId>tfs-parent</artifactId>
  <packaging>pom</packaging>
  <name>Team Foundation Server Plug-in parent</name>
  <version>${revision}${changelist}</version>
  <properties>
    <revision>6.0.0</revision>
    <changelist>-bittner-krull</changelist>
    <!-- Version is required to be compatible with current Pipeline plugin dependencies -->
    <jenkins.version>2.568.1</jenkins.version>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <developers>
    <developer>
      <id>dastahel</id>
      <name>David Staheli</name>
      <email>dastahel@microsoft.com</email>
      <timezone>-5</timezone>
    </developer>
    <developer>
      <id>jpricket</id>
      <name>Jason Prickett</name>
      <email>jpricket@microsoft.com</email>
      <timezone>-5</timezone>
    </developer>
    <developer>
      <id>jeffyoung</id>
      <name>Jeff Young</name>
      <email>jeyou@microsoft.com</email>
      <timezone>-5</timezone>
    </developer>
    <developer>
      <id>jenkinssriramb</id>
      <name>Sriram Balasubramaniyan</name>
      <email>sriramb@microsoft.com</email>
      <timezone>+5</timezone>
    </developer>
    <developer>
      <id>kalyan</id>
      <name>Kalyan</name>
      <email>kasubram@microsoft.com</email>
      <timezone>+5</timezone>
    </developer>
    <developer>
      <id>keljos</id>
      <name>Kellie Jos</name>
      <email>kej@microsoft.com</email>
      <timezone>-5</timezone>
    </developer>
    <developer>
      <id>mosabua</id>
      <name>Manfred Moser</name>
      <email>manfred@simpligility.com</email>
      <timezone>-8</timezone>
    </developer>
    <developer>
      <id>leantk</id>
      <name>Leah Antkiewicz</name>
      <email>leantk@microsoft.com</email>
      <timezone>-5</timezone>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/jenkinsci/tfs-plugin.git</connection>
    <developerConnection>scm:git:https://github.com/jenkinsci/tfs-plugin.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <distributionManagement>
    <snapshotRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/snapshots/</url>
    </snapshotRepository>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/releases/</url>
    </repository>
  </distributionManagement>

  <modules>
    <module>tfs-sdk</module>
    <module>tfs</module>
  </modules>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.6.0</version>
        <configuration>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
          <updatePomFile>true</updatePomFile>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <!-- Jenkins plugin BOM: manages versions of Jenkins plugins -->
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.568.x</artifactId>
                <version>7093.v37de7b_4a_8a_4f</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

     <dependencies>
       <dependency>
         <groupId>org.apache.commons</groupId>
         <artifactId>commons-digester3</artifactId>
         <version>3.2</version>
       </dependency>
     </dependencies>
</project>  
  

